# Generated by Django 2.2 on 2020-01-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã loại')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='Tên Loại')),
                ('category_image', models.ImageField(upload_to='category_image', verbose_name='Hình')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
